find_path(VIKIT_COMMON_INCLUDE_DIR vikit/vision.h PATH_SUFFIXES include)
find_library(VIKIT_COMMON_LIBRARY vikit_common)

if(VIKIT_COMMON_INCLUDE_DIR AND VIKIT_COMMON_LIBRARY)
    set(VIKIT_COMMON_FOUND TRUE)
endif(VIKIT_COMMON_INCLUDE_DIR AND VIKIT_COMMON_LIBRARY)

if(VIKIT_COMMON_FOUND)
    message(STATUS "Vikit found (include: ${VIKIT_COMMON_INCLUDE_DIR}, lib: ${VIKIT_COMMON_LIBRARY})")
endif(VIKIT_COMMON_FOUND)

set(vikit_common_INCLUDE_DIRS ${VIKIT_COMMON_INCLUDE_DIR})
set(vikit_common_LIBRARIES ${VIKIT_COMMON_LIBRARY})
set(vikit_common_FOUND ${VIKIT_COMMON_FOUND})

